FROM openmpi

RUN dnf install -y --setopt=install_weak_deps=false \
                autoconf \
                netcdf-fortran-devel \
                munge \
 && dnf clean all
 
RUN mkdir /usr/include/hdf


# TAU profiler

RUN mkdir -p /tau_installed

RUN git clone https://github.com/ParaToolsInc/taucmdr.git \
 && cd taucmdr \
 && make install INSTALLDIR=/tau_installed

ENV PATH="/tau_installed/bin:${PATH}"
